#!/usr/bin/env python3
"""Regenerate site/_headers with CSP hashes taken from the current index.html.

The Content-Security-Policy pins the one inline <script> and the one inline
<style> by SHA-256 instead of allowing 'unsafe-inline', so run this again
after ANY edit to either block or the browser will refuse to run them.

    python3 site/build-headers.py
"""
import base64
import hashlib
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
html = (HERE / "index.html").read_text()


def sha256(payload: str) -> str:
    return "'sha256-" + base64.b64encode(hashlib.sha256(payload.encode()).digest()).decode() + "'"


scripts = re.findall(r"<script>(.*?)</script>", html, re.S)
styles = re.findall(r"<style>(.*?)</style>", html, re.S)

if not scripts or len(styles) != 1:
    sys.exit(f"expected at least one inline <script> and exactly one <style>, found {len(scripts)} and {len(styles)}")

script_hash = " ".join(sha256(x) for x in scripts)
style_hash = sha256(styles[0])

# Every asset is same-origin: fonts and images are served from this site and
# there is no third-party script, so the policy needs no external origins at all.
csp = "; ".join([
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self'",
    "font-src 'self'",
    f"style-src 'self' {style_hash}",
    f"script-src 'self' {script_hash}",
    "connect-src 'self'",
    "manifest-src 'self'",
    "upgrade-insecure-requests",
])

headers = f"""# Generated by build-headers.py — do not hand-edit the CSP hashes.
# Regenerate after any change to the inline <script> or <style> in index.html.

/*
  Content-Security-Policy: {csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin

# Fingerprint-free filenames, so keep the HTML itself revalidating.
/index.html
  Cache-Control: public, max-age=0, must-revalidate

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
"""

(HERE / "_headers").write_text(headers)
print("wrote _headers")
print("  script-src", script_hash)
print("  style-src ", style_hash)
