#!/usr/bin/env python3
"""Regenerate site/_headers with CSP hashes taken from the current index.html.

The Content-Security-Policy pins the one inline <script> and the one inline
<style> by SHA-256 instead of allowing 'unsafe-inline', so run this again
after ANY edit to either block or the browser will refuse to run them.

    python3 site/build-headers.py
"""
import base64
import hashlib
import pathlib
import re
import sys

# Lives in tools/, not in site/: site/ is the published folder, and a build
# script left there is served from the live domain.
HERE = pathlib.Path(__file__).resolve().parent.parent / "site"
html = (HERE / "index.html").read_text()


def sha256(payload: str) -> str:
    return "'sha256-" + base64.b64encode(hashlib.sha256(payload.encode()).digest()).decode() + "'"


# Comments are removed before anything is matched. A comment that mentions a
# script tag — and one of them does, explaining this very rule — would
# otherwise be found by the search below, which would then run on to the next
# closing tag and hash a span of the file that is not a script at all. The
# page still worked when that happened, since the real hashes were also
# present, but the policy carried a hash for something that does not exist.
scannable = re.sub(r"<!--.*?-->", "", html, flags=re.S)

# Only a tag with no attributes: an inline script with a type is a data block
# (JSON-LD), which the browser does not execute and CSP does not govern.
scripts = re.findall(r"<script>(.*?)</script>", scannable, re.S)
styles = re.findall(r"<style>(.*?)</style>", scannable, re.S)

if not scripts or len(styles) != 1:
    sys.exit(f"expected at least one inline <script> and exactly one <style>, found {len(scripts)} and {len(styles)}")

# Every opening tag must have produced exactly one block. If it did not, a
# match began somewhere that is not a script and ran on to the next closing
# tag, and the hash covers a span of the file that was never executed. The
# page keeps working when that happens — the real hashes are there too — so
# nothing would draw attention to it. Hence the check.
#
# A script may legitimately mention a tag in its own comments, so the text
# inside a block is not evidence of anything; the count is.
for name, blocks in (("script", scripts), ("style", styles)):
    opens = scannable.count(f"<{name}>")
    if opens != len(blocks):
        sys.exit(f"found {opens} <{name}> tags but matched {len(blocks)} blocks; a match ran past a closing tag")

script_hash = " ".join(sha256(x) for x in scripts)
style_hash = sha256(styles[0])

# Every asset is same-origin: fonts, images and the Vanta/three bundles are all
# served from this site, so the policy needs no external origins at all.
csp = "; ".join([
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "img-src 'self'",
    "font-src 'self'",
    f"style-src 'self' {style_hash}",
    f"script-src 'self' {script_hash}",
    "connect-src 'self'",
    "manifest-src 'self'",
    "upgrade-insecure-requests",
])

headers = f"""# Generated by build-headers.py — do not hand-edit the CSP hashes.
# Regenerate after any change to the inline <script> or <style> in index.html.

/*
  Content-Security-Policy: {csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin

# Fingerprint-free filenames, so keep the HTML itself revalidating.
/index.html
  Cache-Control: public, max-age=0, must-revalidate

/fonts/*
  Cache-Control: public, max-age=31536000, immutable

# Not immutable, because these filenames carry no version: a photo replaced
# under the same name has to be able to reach people. A day fresh, then a
# week in which the old one is shown once while the new one is fetched —
# so a returning visitor pays nothing for 230 KB of pictures, and a changed
# picture is never more than a visit behind.
#
# Cross-origin, overriding the same-origin above, and this one is load-bearing:
# the ZUNO wordmark in every mail the shop sends is fetched from here by a
# mail client, which is not an origin on worldofzuno.com. Apple Mail renders
# with WebKit, WebKit enforces the policy, and same-origin turned the logo
# into a broken-image placeholder in the first order confirmation that went
# out on the real domain. These are public brand assets meant to be shown
# elsewhere; the policy protects nothing here that is worth a blank logo.
/img/*
  Cache-Control: public, max-age=86400, stale-while-revalidate=604800
  Cross-Origin-Resource-Policy: cross-origin

# Same reason, one file: the preview picture social sites and chat apps show
# for a shared link. They mostly fetch it server-side, where the policy does
# not apply, but the ones that render it in a browser are the ones that would
# show a hole.
/og-image.jpg
  Cross-Origin-Resource-Policy: cross-origin

# The library filenames carry their version, so a new one is a new URL.
/js/*
  Cache-Control: public, max-age=31536000, immutable

# The back office. It is behind a key, but a key is not a reason to let it be
# indexed, cached or archived — robots.txt disallows it too, and the page
# carries its own noindex meta. Belt, braces and a third thing, because a
# search result for "ZUNO back office" would be an invitation.
/admin/*
  X-Robots-Tag: noindex, nofollow, noarchive
  Cache-Control: no-store
"""

(HERE / "_headers").write_text(headers)
print("wrote _headers")
print("  script-src", script_hash)
print("  style-src ", style_hash)
